### ISSUE TITLE
Makefile breaks with latest Replicated CLI release on MacOS

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/replicated-automation#23]
## Description
The Makefile which y'all recommend using for development broke with the latest replicated cli release (on macOS at least). it was looking for _amd64 release assets and it's now darwin_all

## Reproduction Steps
Use makefile linked below

## Expected Behavior
Makefile should look for `darwin_all`

## Customer Impact
The recommended development make doesn't work

## Possible Solution
- Update the make file
- Remove makefile & update docs to use `replicated` CLI installed from another method

## Environment
KOTS on MacOS

## Additional Information
https://github.com/replicatedhq/replicated/releases/tag/v0.39.2
https://raw.githubusercontent.com/replicatedhq/replicated-automation/master/vendor/helm-influxdb/kots/Makefile
https://docs.replicated.com/vendor/tutorial-ci-cd-integration

**Comment by adamancini** [comment]
cc @beck-at-replicated @dexhorthy

**Comment by dexhorthy** [comment]
i mean the bottom line is this is meant as an example and not intended for production use. Let's just remove the CLI install logic
